name: CI/CD Pipeline
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker images
        run: |
          docker build -t product-service ./product-service
          docker build -t user-service ./user-service
          docker build -t inventory-service ./inventory-service
          docker build -t order-service ./order-service
          docker build -t recommendation-service ./recommendation-service
        